/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class androiddm_dbscan */

#ifndef _Included_androiddm_dbscan
#define _Included_androiddm_dbscan
#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT jshort JNICALL
Java_com_example_dmocl_dbscan_dbscan_1c(JNIEnv*, jclass, jshortArray, jfloatArray,
                                        jfloat, jint, jint );

JNIEXPORT jshort JNICALL
Java_com_example_dmocl_dbscan_dbscan_1c_1gpu(JNIEnv*, jclass, jshortArray,
                                             jfloatArray, jfloat, jint, jint, jlongArray );

JNIEXPORT jshort JNICALL
Java_com_example_dmocl_dbscan_dbscan_1c_1phtreads
  (JNIEnv*, jclass, jshortArray, jfloatArray, jfloat, jint, jint, jint, jlongArray );


#ifdef __cplusplus
}
#endif
#endif
