/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class androiddm_kmeans */

#ifndef _Included_androiddm_kmeans
#define _Included_androiddm_kmeans
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     androiddm_kmeans
 * Method:    kmeans_c
 * Signature: ([S[FFII)S
 */
JNIEXPORT jshort JNICALL Java_com_example_dmocl_kmeans_kmeans_1c
  (JNIEnv *, jclass, jshortArray, jfloatArray, jfloat, jint, jint);

/*
 * Class:     androiddm_kmeans
 * Method:    kmeans_c_gpu
 * Signature: ([S[FFII)S
 */
JNIEXPORT jshort JNICALL Java_com_example_dmocl_kmeans_kmeans_1c_1gpu
  (JNIEnv *, jclass, jshortArray, jfloatArray, jfloat, jint, jint, jlongArray );

/*
 * Class:     androiddm_kmeans
 * Method:    kmeans_c_phtreads
 * Signature: ([S[FFIII)S
 */
JNIEXPORT jshort JNICALL Java_com_example_dmocl_kmeans_kmeans_1c_1phtreads
  (JNIEnv *, jclass, jshortArray, jfloatArray, jfloat, jint, jint, jint, jlongArray );

#ifdef __cplusplus
}
#endif
#endif

